import { useNavigate, useParams } from 'react-router-dom'
import { AppHeader } from '../components/AppHeader'
import { RiskBadge } from '../components/RiskBadge'
import { FeatureBar } from '../components/FeatureBar'
import { getPatient } from '../lib/storage'

export function FeatureContribution() {
  const navigate = useNavigate()
  const { id } = useParams<{ id: string }>()
  const patient = id ? getPatient(id) : null
  const latest = patient?.predictions.at(-1)

  if (!patient || !latest) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-500">No prediction data available.</p>
      </div>
    )
  }

  const prob = latest.failureProbability
  const contributions = latest.contributions
  const maxDelta = Math.max(...contributions.map(c => c.delta), 0.001)

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <AppHeader backLabel="Back to Patient Profile" onBack={() => navigate(`/patient/${id}`)} />

      <main className="flex-1 px-4 pb-24 pt-4 space-y-4">
        <div>
          <h2 className="font-bold text-gray-900 text-lg">Risk Factor Analysis</h2>
          <p className="text-sm text-gray-500">What's driving {patient.name}'s failure risk</p>
        </div>

        <div className="bg-white border border-gray-100 rounded-xl p-4 shadow-sm flex items-center gap-3">
          <span className="text-sm font-semibold text-gray-600">Overall Risk:</span>
          <span className="text-2xl font-extrabold text-red-500">{Math.round(prob * 100)}%</span>
          <RiskBadge probability={prob} size="lg" />
        </div>

        <div className="bg-white border border-gray-100 rounded-xl p-4 shadow-sm">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Feature Contributions</p>

          <div className="space-y-1">
            {contributions.map(c => (
              <FeatureBar
                key={c.feature}
                feature={c.feature}
                delta={c.delta}
                direction={c.direction}
                maxDelta={maxDelta}
              />
            ))}
          </div>

          <div className="flex gap-4 mt-4 pt-3 border-t border-gray-100">
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded bg-red-400" />
              <span className="text-xs text-gray-500">Increases failure risk</span>
            </div>
            <div className="flex items-center gap-1.5">
              <div className="w-3 h-3 rounded bg-green-400" />
              <span className="text-xs text-gray-500">Decreases failure risk</span>
            </div>
          </div>
        </div>

        <div className="bg-blue-50 border border-blue-100 rounded-xl p-3 flex gap-2">
          <span className="text-blue-500">ℹ</span>
          <p className="text-xs text-blue-700">
            This explanation is generated by the AI model. Final clinical decisions must be made by qualified healthcare professionals.
          </p>
        </div>
      </main>

      <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 px-4 py-4">
        <button onClick={() => navigate(`/patient/${id}`)}
          className="w-full border border-gray-200 text-gray-700 py-3.5 rounded-xl font-semibold text-sm">
          ← Back
        </button>
      </div>
    </div>
  )
}
