import type { Patient } from '../lib/storage'
import type { ContributionResult } from '../lib/inference'
import { useStreamingInterpretation } from '../hooks/useStreamingInterpretation'

interface ClinicalInterpretationProps {
  patient: Patient | null
  result: ContributionResult | null
}

function renderText(text: string) {
  const paragraphs = text.split(/\n\n+/)
  return paragraphs.map((para, i) => {
    const parts = para.split(/\*\*/)
    const nodes = parts.map((part, j) =>
      j % 2 === 1 ? <strong key={j}>{part}</strong> : part
    )
    return <p key={i} className="text-sm text-gray-700 mb-2 last:mb-0">{nodes}</p>
  })
}

export function ClinicalInterpretation({ patient, result }: ClinicalInterpretationProps) {
  const { text, isStreaming, isComplete, error, retry } = useStreamingInterpretation(patient, result)

  if (patient === null || result === null) return null

  return (
    <div className="bg-white border border-gray-100 rounded-xl p-4 shadow-sm">
      <div className="flex items-center gap-2 mb-3">
        <p className="text-sm font-semibold text-gray-800">🧠 AI Clinical Interpretation</p>
        <span className="text-xs px-2 py-0.5 rounded-full bg-primary/10 text-primary font-medium">MedGemma</span>
      </div>

      {!isComplete && !error && text.length === 0 && (
        <div className="space-y-2 animate-pulse">
          <div className="h-3 bg-gray-200 rounded w-full" />
          <div className="h-3 bg-gray-200 rounded w-5/6" />
          <div className="h-3 bg-gray-200 rounded w-4/6" />
        </div>
      )}

      {text.length > 0 && (
        <div>{renderText(text)}</div>
      )}

      {isComplete && (
        <p className="text-xs text-gray-400 italic mt-3">
          ⚕ Generated by MedGemma 1.5 4B · For clinical decision support only.
        </p>
      )}

      {error && (
        <div>
          <p className="text-sm text-gray-500">AI interpretation unavailable.</p>
          <button
            onClick={retry}
            className="mt-2 text-sm text-primary border border-primary rounded px-3 py-1"
          >
            Try again
          </button>
        </div>
      )}
    </div>
  )
}
